### PR TITLE
traffic 和trend调整为单列

### LINKED ISSUE #393: 流量统计图表双列布局下左侧数值显示溢出
RT单列下正常，双列左侧溢出（测试显示器分辨率1080p/2K）
cb14c566079db4b4ee89397c3ec2801d
780f92fb1c311b0a70115d690a9345c2

### PR DESCRIPTION
**Pull request by Gaojianli**
close #393 

## Summary by CodeRabbit

- **New Features**
	- Enhanced ban management system with support for shadow banning, allowing users to apply standard and shadow bans based on configuration.
	- Improved integration with the qBittorrent API for more granular control over peer bans.

- **Style**
	- Redesigned layout of the charts component for improved visual prominence of "trends" and "traffic" charts.
	- Adjusted layout and presentation of the traffic and trends components for better user experience.

- **Chores**
	- Reorganized import statements in the charts components for better code clarity.

### CODE REVIEW

**Comment by Ghost-chu** [comment]
如果调整为了单列，是否可以考虑显示更长时间的数据？（因为可供显示的屏幕空间翻了一倍）

**Comment by Gaojianli** [comment]
> 如果调整为了单列，是否可以考虑显示更长时间的数据？（因为可供显示的屏幕空间翻了一倍）

你改一下吧，要综合参考加载速度

**Review by XiaoXice — APPROVED** [review]

**Comment by paulzzh** [comment]
怎么有shadowban相关的改动进来了

**Comment by Ghost-chu** [comment]
> 怎么有shadowban相关的改动进来了

看到不止我一个因为CR导致频繁切换分支commit到错误分支里，我就放心了

**Review by Ghost-chu — CHANGES_REQUESTED** [review]
混进来了不该有的 commit，能把这个 shadowban 的挪出去吗

**Pull request merged**
